<div style="color: #000000; background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: #ffffff; background-position: initial initial; background-repeat: initial initial; margin: 8px;">
<h3 style="font-size: 1.17em; text-align: center;">ESCUELA TÉCNICA SUPERIOR DE INGENIERÍA INFORMÁTICA</h3>
<h3 style="font-size: 1.17em; text-align: center;">UNIVERSIDAD DE SEVILLA</h3>
<h4 style="font-size: 1em; text-align: center;"><strong>ÁLGEBRA LINEAL Y NUMÉRICA</strong></h4>
<h3 style="font-size: 1.17em;">Introducción a SageMath y su uso en Álgebra Lineal y Numérica</h3>
<p>En esta primera sesión nos marcamos los siguientes objetivos:</p>
<ul>
<li>Dar una introducción al software SageMath y al <a href="#intro">manejo de esta interfaz</a>.</li>
<li>Familiarizarnos con los <a href="#basicos">procedimientos básicos</a> del álgebra lineal trabajando con SageMath.</li>
<li>Trabajar con el método de <a href="#eliminacion">eliminación gaussiana</a> y el algoritmo de Gauss-Jordan.</li>
<li>Conocer algunas posibilidades de SageMath para trabajar con diferentes <a href="#anillos">anillos de números</a>.</li>
<li>Ilustrar algunas <a href="#aplicaciones">aplicaciones prácticas</a> de la resolución de sistemas de ecuaciones lineales a problemas reales.</li>
</ul>
<p>La práctica finaliza con la realización por parte del alumnado de un <a href="#cuestionario">cuestionario</a> personalizado.</p>
</div>

<h2><a name="intro"></a> Introducción a SageMath</h2>
<h3 style="font-size: 1.17em;">Breve descripción</h3>
<p>SageMath es un paquete de <strong>software matemático libre y de código abierto</strong> bajo licencia GNU GPL. En realidad SageMath engloba, bajo una misma interfaz, a cerca de un centenar de paquetes de software matemático libre, poniéndolos a disposición del usuario de forma transparente. El lenguaje de programación empleado para ello es <strong>Python </strong>(actualmente Python 2.7 para versiones de SageMath inferiores a la 9 y Python 3 a partir de la versión 9 de SageMath) y en ese sentido, el lenguaje propio de SageMath es compatible en un 99% con Python.  Intentaremos dar una pequeña introducción al manejo de SageMath desde la asignatura de Álgebra Lineal y Numérica.</p>
<h3 style="font-size: 1.17em;">Manejo de esta interfaz<span style="font-weight: normal; font-size: small;"> <br /></span></h3>
<p>Este documento es un ejemplo de cuaderno (<strong>notebook</strong>) en SageMath, en formato `.ipynb` (ipython notebook), visualizado por medio del interfaz *Jupyter*. Si has seguido una introducción a Python en la asignatura <strong>Fundamentos de la programación</strong> o utilizaste SageMath en la asignatura <strong>Cálculo Infinitesimal y Numérico</strong>, ya utilizaste el interfaz <strong>Jupyter</strong> y puedes pasar a la sección siguiente de este notebook.

Hay dos tipos de recuadros o espacios (celdas)  a lo largo del documento:
* los que no son ejecutables, que normalmente contienen texto, como este espacio que estás leyendo. Son celdas "Markdown" ya que se utiliza la [sintaxis Markdown](https://es.wikipedia.org/wiki/Markdown) utilizada también en muchos wikis.
* y  recuadros ejecutables (contienen instrucciones ó código de SageMath).

Esta celda es una celda de texto. Para editar esta celda, haz doble-click en la celda. Puedes guardar y visualizar tus modificaciones con *Shift+Enter*.  

La sintaxis Markdown permite
* insertar facilmente listas, hyperenlaces...
* **enfatizar** de *varias maneras* ...

Se puede utilizar también <font color="red">sintaxís HTML </font>. <br /> <br />
Para escribir formulas de matemáticas, se puede utilizar la sintaxís [LaTeX](https://es.wikipedia.org/wiki/LaTeX). Por ejemplo: 
$$\int_0^{\infty} e^{-\frac{x^2}{2}} dx = \sqrt{\frac{\pi}{2}}.$$

>*Haz doble-click en esta celda para ver como este texto fue elaborado con Markdown, HTML y LaTeX.*

La celda que viene a continuación es una celda de código. Haz click en la celda  y pulsa MAYÚSCULAS +  ENTER para ejecutar el código. Si SageMath devuelve un resultado, lo hace en el espacio inferior, justo debajo de la celda.

In [9]:
print("Hello world!")
print("1+1=", 1+1)

Hello world!
1+1= 2


Puedes 
* modificar el tipo de una celda (de texto/de código) por medio del menú "Cell/Cell Type", 
* insertar nuevas celdas con el menú "Insert" o pinchando en el icono "+" debajo del menú "File". La nueva celda insertada con "+" es, por defecto, una celda de comandos; la puedes convertir en celda de texto colocando el ratón en el margen izquierdo y tecleando allí "m". 
* eliminar, copiar, mover celdas con el menú "Edit".

Para guardar las modificaciones realizadas en el cuaderno, utiliza el menu "File/Save and Checkpoint" o pincha en el icono de disco al lado del menu "File". Para cerrar el cuaderno, utiliza "File/Close and halt".

<h3>Ejemplo 1:</h3>
<p>A continuación, ejecuta las instrucciones de las siguientes celdas y experimenta con la inserción de nuevas celdas ejecutables y de texto.</p>

In [4]:
5 + 2*3 -(4 + 3)

4

In [5]:
5 - 3*2; 2 + 3^2; 1/3 + 1/2

5/6

In [6]:
x = 7; y = 3
2 + 3
5 + x + y

15

<div style="color: #000000; background-image: initial; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: #ffffff; background-position: initial initial; background-repeat: initial initial; margin: 8px;">
<p>SageMath utiliza un lenguaje interpretado y orientado a objetos. En SageMath hay <span style="color: #0000ff;">funciones</span> y <span style="color: #0000ff;">métodos</span>. Para usar una función escribimos el nombre de la función y entre parántesis el objeto al que se le aplica la función. Si usamos un método, primero escribimos el objeto sobre el que se va a actuar, a continuación un punto y finalmente el método, con paréntesis, en cuyo interior se pueden escribir las opciones (en caso necesario).</p>
<p>En el siguiente ejemplo hemos usado  la función <span style="color: #0000ff;">sqrt( )</span> para hallar la raiz cuadrada del número 2 y la función <span style="color: #0000ff;">n( )</span> para hallar una aproximación numérica en coma flotante. Ésta última también actúa como un método, aplicable al resultado numérico; como opción, en el último caso, hemos precisado el número de cifras decimales con <span style="color: #0000ff;">digits</span>.</p>
</div>

In [7]:
sqrt(2)                  # usamos la función sqrt() sobre el objeto 2
n(sqrt(2))               # usamos la función n() sobre el objeto sqrt(2)
sqrt(2).n()              # al objeto sqrt(2) le aplicamos el método n()
n(sqrt(2), digits = 7)   # aplicamos la función n(), la cual actúa sobre el objeto sqrt(2) y utiliza el parámetro opcional digits=7

1.414214

<p>Podemos obtener una representación de los resultados más amigable con la función  <span style="color: #0000ff;">show()</span>:</p>

In [10]:
show(sqrt(2)/ 5)

1/5*sqrt(2)

## Autocompletar y ayuda

<p>La notación de función nos resulta más próxima a la escritura en Matemáticas. Sin embargo, los métodos o atributos tienen una ventaja adicional: como primero tenemos que escribir el objeto, SageMath "sabe" qué métodos se pueden aplicar a dicho objeto. Si escribimos un objeto, a continuación un punto y pulsamos el tabulador nos aparece un listado con todos los métodos que se pueden aplicar a dicho objeto. Si hemos empezado a escribir el objeto y pulsamos el tabulador, el programa completará el nombre o nos dará las diversas posibilidades, si hay más de una.</p>
<p>Para obtener ayuda sobre un método o función sustituimos los paréntesis por el signo de interrogación "?" y pulsamos el tabulador.</p>
<p>La asignación de un valor a cierta variable en SageMath se hace con el signo de la igualdad, uno solo.</p>

In [14]:
M = matrix([[1,2],[3,4]])
M

[1 2]
[3 4]

A continuación, buscamos un método para obtener la inversa de $M$. Empezamos escribiendo `M.inv`, esperando que el método correcto empieze por `inv`, y a continuación presionamos la tecla de tabulación: SAGE ofrece las maneras posibles de completar.

> &#9758; Coloca el ratón all final del `M.inv` que sigue y presiona la tecla de tabulación. Calcula luego la inversa de $M$.

In [15]:
M.inv

AttributeError: 'sage.matrix.matrix_integer_dense.Matrix_integer_dense' object has no attribute 'inv'

Obtenemos ayuda sobre un método con el ?

> &#9758; ejecuta la celda que sigue para saber más sobre el método `inverse`.

In [13]:
M.inverse?

/opt/sagemath-9.2/local/lib/python3.7/site-packages/docutils/writers/latex2e/__init__.py:2978: DeprecationWarning: invalid escape sequence \l
  self.out.append('}] \leavevmode ')


<h2><a name="basicos"></a>Procedimientos básicos del Álgebra Lineal</h2>
<p>Vamos a familiarizarnos con los procedimientos y cálculos básicos que se emplean en el álgebra lineal.</p>
<p>Empezamos con la introducción de matrices y vectores:</p>

* A continuación guardamos en la memoria una variable $A$ que contiene una matriz no singular de orden $3\times 3$.
* Similarmente, $b$ se corresponde con un vector de $\mathbb{R}^3$.

In [1]:
A = matrix([[1, 1, 1, 1, 0, 0],[0, -1, 0, -1, 7, 0],[0, 0, -1, -1, 1, 1],[0, 0, 0, 1, -8, -1], [0, 0, 0, 0, 1, -1/3],[0, 0, 0, 0, 0, -46/3]])
A

[    1     1     1     1     0     0]
[    0    -1     0    -1     7     0]
[    0     0    -1    -1     1     1]
[    0     0     0     1    -8    -1]
[    0     0     0     0     1  -1/3]
[    0     0     0     0     0 -46/3]

In [3]:
b = vector([0, 0, 0, 0, 0, 0])
b

(0, 0, 0, 0, 0, 0)

In [4]:
A.solve_right(b)

(0, 0, 0, 0, 0, 0)

In [9]:
A = matrix([[1, 1, 1, 1, 0, 0],[0, -1, 0, -1, 7, 0],[0, 0, -1, -1, 1, 1]])
A

[ 1  1  1  1  0  0]
[ 0 -1  0 -1  7  0]
[ 0  0 -1 -1  1  1]

In [10]:
b = vector([0, 0, 0])
b

(0, 0, 0)

In [11]:
A.solve_right(b)

(0, 0, 0, 0, 0, 0)

In [5]:
A = matrix([[1, 1, 2, 2, 3, 3],[3, 0, 0, 4, 0, 5],[4, 0, 6, 0, 7, 1],[-4, 1, 1, 1, 0, 0],[-3, 2, -1, 0, 1, 0], [-12, 7, 3, 0, 0, 1]])
show(A)
A.rank()

[  1   1   2   2   3   3]
[  3   0   0   4   0   5]
[  4   0   6   0   7   1]
[ -4   1   1   1   0   0]
[ -3   2  -1   0   1   0]
[-12   7   3   0   0   1]

TypeError: no conversion of this rational to integer

In [3]:
A = matrix([[1, 1, 1, 1, 0, 0],[1, 1, 0, 0, 1, 1], [1, 0, 1, 0, 7, 0],[1, 1, 2, 2, 3, 3],[3, 0, 0, 4, 0, 5],[4, 0, 6, 0, 7, 0]])
show(A)
A.rank()

[1 1 1 1 0 0]
[1 1 0 0 1 1]
[1 0 1 0 7 0]
[1 1 2 2 3 3]
[3 0 0 4 0 5]
[4 0 6 0 7 0]

6

**Para obtener una solución de un sistema lineal** $Ax=b$ , primero debemos haber guardado los datos de la matriz $A$ en formato matriz y los datos del vector de términos independientes $b$ en formato vector. Aplicamos a A el método `.solve_right` con argumento adicional `b `. Es importante tener en cuenta que dicho método tan solo proporciona una solución, caso de que exista, aun cuando haya infinitas posibilidades.

In [21]:
A.solve_right(b)

(2, 1, -1)

<p>Comprobamos que $A$ es no singular hallando su determinante (en este caso, la solución es única):</p>

In [22]:
A.det()  # el determinante no se anula (A es no singular)

299/3

Así obtenemos la **traspuesta** $A^t$ de la matriz $A$:

In [23]:
A.transpose()

[  2  -1 1/2]
[  1   6   1]
[1/3   2   8]

 y **la inversa** $A^{-1}$ de $A$:

In [24]:
A.inverse()

[   6/13   -1/13       0]
[ 27/299  95/598   -1/23]
[-12/299  -9/598    3/23]

<p>Los vectores actúan indistintamente como filas o columnas, sin necesidad de introducir órdenes para trasponerlos:</p>

In [25]:
b*A

(13/3, 32/3, -382/9)

In [17]:
A*b

(28/3, -14/3, -131/3)

<p>Calculamos $A^{-1}b$</p>

In [26]:
A.inverse()*b

(2, 1, -1)

<p>Podemos convertir un vector en una matriz fila (fila = "row" en inglés):</p>

In [27]:
show(b)
mb = b.row()
show(mb)

(14/3, 2, -6)

[14/3    2   -6]

<p>O en una matriz columna:</p>

In [28]:
b.column()

[14/3]
[   2]
[  -6]

In [29]:
show(b)
mbt = b.column()
show(mbt)

(14/3, 2, -6)

[14/3]
[   2]
[  -6]

**Algunos datos básicos de una matriz y extracción de vectores filas o columnas.**
<p>Obsérvese que en SageMath se enumeran los elementos empezando por 0:</p>

In [30]:
print("rango:", A.rank())
print("nº columnas:", A.ncols())
print("nº filas:", A.nrows())
print("3ª fila:", A.row(2))          ### en Sage se empieza a contar por 0
print("1ª columna:", A.column(0))

rango: 3
nº columnas: 3
nº filas: 3
3ª fila: (1/2, 1, 8)
1ª columna: (2, -1, 1/2)


Extracción de una **submatriz**:

In [31]:
B = matrix([[1, -1, 4],[-1, 0, 3],[5, -2, 4]])
show(B)


[ 1 -1  4]
[-1  0  3]
[ 5 -2  4]

In [32]:
B2 = B.matrix_from_rows_and_columns([1,2],[0,1])  # filas 1 y 2, columnas 0 y 1
show(B2)

[-1  0]
[ 5 -2]

**Agrupar** dos matrices por filas:

In [33]:
A.augment(B)

[  2   1 1/3   1  -1   4]
[ -1   6   2  -1   0   3]
[1/2   1   8   5  -2   4]

Se puede hacer también guardando una "separación" entre los dos bloques $A$ y $B$:

In [34]:
block_matrix([[A, B]])

[  2   1 1/3|  1  -1   4]
[ -1   6   2| -1   0   3]
[1/2   1   8|  5  -2   4]

In [27]:
show(block_matrix([[A, B]]))

[  2   1 1/3|  1  -1   4]
[ -1   6   2| -1   0   3]
[1/2   1   8|  5  -2   4]

<p>Agrupar dos matrices por columnas:</p>

In [35]:
A.stack(B)

[  2   1 1/3]
[ -1   6   2]
[1/2   1   8]
[  1  -1   4]
[ -1   0   3]
[  5  -2   4]

También:

In [36]:
show(block_matrix([[A],[B]]))

[  2   1 1/3]
[ -1   6   2]
[1/2   1   8]
[-----------]
[  1  -1   4]
[ -1   0   3]
[  5  -2   4]

La **matriz identidad** de orden 3:

In [37]:
identity_matrix(3)

[1 0 0]
[0 1 0]
[0 0 1]

Una **matriz diagonal**:

In [38]:
diagonal_matrix(3, [2, -3, 4])

[ 2  0  0]
[ 0 -3  0]
[ 0  0  4]

**Matriz nula** de orden $3 \times 2$:

In [39]:
matrix(3, 2, 0)

[0 0]
[0 0]
[0 0]

<h2 style="font-size: 1.5em;"><a name="eliminacion"></a>Eliminación gaussiana y algoritmo de Gauss-Jordan</h2>
<p>Hemos visto en clase los siguientes teoremas:</p>
<p><strong>Teorema 1</strong>.(algoritmo de eliminación gaussiana)  Para cualquier matriz $A$ de orden $m \times
n$ existe otra matriz cuadrada $F$ de orden $m$ tal que $F\cdot A=U$, siendo $U$ una matriz escalonada.</p>
<p><strong>Teorema 2</strong>. (algoritmo de Gauss-Jordan) En el resultado anterior, podemos conseguir, además, que $U$ sea una matriz escalonada reducida.</p>
<p> </p>
<p>Como bien sabemos, los algoritmos correspondientes que resuelven ambos problemas se basan en la aplicación de transformaciones elementales fila sobre la matriz ampliada del sistema.</p>
<p> </p>
<p>SageMath incorpora algunas instrucciones relacionadas con las transformaciones elementales entre filas de una matriz y con el proceso de escalonamiento para obtener una matriz escalonada canónica.</p>

In [40]:
A = matrix([[2, 1, 1/3], [-1, 6, 2], [1/2, 1, 8]])
A

[  2   1 1/3]
[ -1   6   2]
[1/2   1   8]

<p>Hacemos una copia de la matriz $A$ y aplicamos un intercambio de filas:</p>

In [41]:
B = copy(A);
B.swap_rows(1, 2);  #  F2 <-> F3 (empezando a contar desde 0, convención matemática)
show(A)
show(B)

[  2   1 1/3]
[ -1   6   2]
[1/2   1   8]

[  2   1 1/3]
[1/2   1   8]
[ -1   6   2]

<p>Hacemos una copia de la matriz $A$ y multiplicamos una fila por un escalar:</p>

In [42]:
B = copy(A)
B.rescale_row(1, -2) # F2 <- -2 F2
show(A)
show(B)

[  2   1 1/3]
[ -1   6   2]
[1/2   1   8]

[  2   1 1/3]
[  2 -12  -4]
[1/2   1   8]

<p>Hacemos una copia de la matriz $A$ y a una fila le sumamos un múltiplo de otra fila:</p>

In [43]:
B = copy(A)
B.add_multiple_of_row(2, 1, -1) # F3 <- F3 - F2
show(A)
show(B)

[  2   1 1/3]
[ -1   6   2]
[1/2   1   8]

[  2   1 1/3]
[ -1   6   2]
[3/2  -5   6]

<p>Dado el sistema lineal $Ax=b$, construimos la matriz ampliada $M$ del sistema:</p>

In [44]:
b = vector([14/3, 2, -6])

M = A.augment(b.column())
show(M)

[   2    1  1/3 14/3]
[  -1    6    2    2]
[ 1/2    1    8   -6]

<p>Resolución del sistema mediante eliminación gaussiana aplicada a la matriz ampliada, obteniendo la <strong>forma escalonada canónica (o "reducida")</strong>:</p>

In [45]:
show(M.echelon_form())

[ 1  0  0  2]
[ 0  1  0  1]
[ 0  0  1 -1]

<h3>Transformaciones elementales <em>(ad hoc)</em></h3>
<p>Para hacer más sencilla la sintaxis de las instrucciones para aplicar transformaciones elementales por filas o culumnas sobre una matriz, hemos creado nuevas funciones. En esta versión, las filas y columnas se enumeran comenzando por 1, lo que corresponde a las convenciones en matemáticas.</p>
<p>Las siguientes funciones, aplicadas sobre una matriz, producen transformaciones elementales:</p>
<p><span style="color: #0000ff;">Fij(A,i,j)</span>   equivale a la transformación elemental fila $F_{i,j}$ aplicada sobre la matriz $A$</p>
<p><span style="color: #0000ff;">Fia(A,i,a)</span>   equivale a la transformación elemental fila $F_{i}(a)$ aplicada sobre la matriz $A$</p>
<p><span style="color: #0000ff;">Fija(A,i,j,a)</span>   equivale a la transformación elemental fila $F_{i,j}(a)$ aplicada sobre la matriz $A$</p>
<p>Existe la versión equivalente para transformaciones elementales por columnas cambiando la F inicial por C:</p>
<p><span style="color: #0000ff;">Cij(A,i,j)</span>,   <span style="color: #0000ff;">Cia(A,i,a)</span>,   <span style="color: #0000ff;">Cija(A,i,j,a)</span></p>

In [46]:

def Fij(M, i, j):
    M.swap_rows(i - 1, j - 1)
    return M

def Fia(M, i, a):
    M.rescale_row(i - 1, a)
    return M

def Fija(M, i, j, a):
    M.add_multiple_of_row(i - 1, j -1, a)
    return M

def Cij(M, i, j):
    (M.transpose()).swap_rows(i - 1, j - 1)
    return M

def Cia(M, i, a):
    M.rescale_col(i - 1, a)
    return M

def Cija(M, i, j, a):
    M.add_multiple_of_column(i - 1, j - 1, a)
    return M

<p>A modo de ejemplo, retomamos la matriz ampliada del sistema anterior y la escalonamos paso a paso:</p>

In [47]:
A = matrix([[2, 1, 1/3], [-1, 6, 2], [1/2, 1, 8]])
b = vector([14/3, 2, -6])
M = A.augment(b.column())
show(M)

[   2    1  1/3 14/3]
[  -1    6    2    2]
[ 1/2    1    8   -6]

In [48]:
Fija(M, 2, 1, 1/2)

[   2    1  1/3 14/3]
[   0 13/2 13/6 13/3]
[ 1/2    1    8   -6]

In [49]:
Fia(M, 2, 1/13)

[   2    1  1/3 14/3]
[   0  1/2  1/6  1/3]
[ 1/2    1    8   -6]

In [50]:
Fija(M, 3, 1, -1/4)

[    2     1   1/3  14/3]
[    0   1/2   1/6   1/3]
[    0   3/4 95/12 -43/6]

In [51]:
Fija(M, 3, 2, (-3/4)/(1/2))

[    2     1   1/3  14/3]
[    0   1/2   1/6   1/3]
[    0     0  23/3 -23/3]

In [52]:
Fia(M, 3, 3/23)

[   2    1  1/3 14/3]
[   0  1/2  1/6  1/3]
[   0    0    1   -1]

In [53]:
Fija(M, 2, 3, -1/6)

[   2    1  1/3 14/3]
[   0  1/2    0  1/2]
[   0    0    1   -1]

In [54]:
Fija(M, 1, 3, -1/3)

[  2   1   0   5]
[  0 1/2   0 1/2]
[  0   0   1  -1]

In [55]:
Fia(M, 2, 2)

[ 2  1  0  5]
[ 0  1  0  1]
[ 0  0  1 -1]

In [56]:
Fija(M, 1, 2, -1)

[ 2  0  0  4]
[ 0  1  0  1]
[ 0  0  1 -1]

In [57]:
Fia(M, 1, 1/2)

[ 1  0  0  2]
[ 0  1  0  1]
[ 0  0  1 -1]

<p>En el mismo sentido, de simpificar la sintaxis y ampliar las posibilidades de la función <span style="color: #0000ff;">echelon_form</span>, hemos creado una nueva función que aplicada sobre una matriz nos proporcione su forma escalonada y, opcionalmente, nos aporte información sobre las transformaciones realizadas durante el procedimiento.</p>
<p>La función <span style="color: #0000ff;">forma_escalonada( A)</span> nos permite obtener tanto las matrices $F$ y $U$  de la descomposición $FA=U$ como la secuencia de transformaciones elementales por filas que reproducen el proceso seguido para escalonar la matriz $A$. Admite las siguientes opciones y parámetros:</p>
<p style="text-align: center;"><span style="color: #0000ff;">F, U =forma_escalonada(A, canonica?, transformaciones?)</span></p>
<p>donde</p>
<ul>
<li><span style="color: #0000ff;">canonica?</span>  es un parámetro opcional que puede ser <span style="color: #0000ff;">True</span> para obtener la forma escalonada canónica y <span style="color: #0000ff;">False</span> para forma escalonada simple</li>
<li><span style="color: #0000ff;">transformaciones?</span> es un parámetro opcional que puede ser <span style="color: #0000ff;">True </span>para que se proporcione la lista de transformaciones elementales filas que se han realizado y <span style="color: #0000ff;">False </span>para que se omitan.</li>
</ul>
<p>Por defecto, <span style="color: #0000ff;">F, U = forma_escalonada(A)  </span>proporciona la forma escalonada simple, sin mostrar las transformaciones elementales.</p>


In [3]:
def forma_escalonada(M, canon = False, ver_transfo = False):
    """forma escalonada de una matriz - Práctica 1 de ALN."""
    A  = copy(M)
    m  = A.nrows() # número de filas
    n  = A.ncols() # número de columnas
    mindim = min(m, n)
    lista_transfos = []                         # Lista que recordará las operaciones realizadas.
    F  = copy(identity_matrix(base_ring(A), m)) 
    s  = -1
    for k in range(mindim):
        r = k      # r: indice de fila
        s = s + 1  # s: indice de columna
        # Buscamos pivote  en filas a partir de k ...
        while (r < m) and (s < n) and (A[r, s] == 0):
            r = r + 1             # ... en primer lugar en la misma columna s.
            if r == m:            # r ha superado el indice máximo de fila, que es m-1
                s = s + 1;r = k   # pasamos a la columna siguiente
        if (r < m) and (s < n):   # Si hemos encontrado un pivote...
            if (r != k):          #    Si el pivote no está en la primera fila considerada...  
                A.swap_rows(k, r) #    ... lo colocamos allí (fila k)
                F.swap_rows(k, r)
                lista_transfos.append( ('swap',(k+1,r+1)) )
            piv = A[k, s]             # Valor del pivote. Su posicion es ahora: fila k, col s.
            for t in range(k + 1, m): # reducimos los coeficientes DEBAJO del pivote.
                multip = A[t, s]*piv^-1 
                if multip != 0:
                    A[t, s] = 0
                    F[t] = F[t] - multip*F[k]
                    lista_transfos.append( ('combination', (t+1, k+1, -multip)))
                    for v in range(s + 1, n):
                        A[t, v] = A[t, v] - multip*A[k, v]
            if canon:    ## si queremos la forma canonica...
                for t in range(k):   # reducimos los coeficientes que estan ENCIMA del pivote
                    multip = A[t, s]*piv^(-1)
                    if multip != 0:
                        A[t, s] = 0
                        F[t] = F[t] - multip*F[k]
                        lista_transfos.append( ('combination',(t+1, k+1, -multip)))
                        for v in range(s + 1, n):
                            A[t, v] = A[t, v] - multip*A[k, v]
                F[k] = F[k]*piv^(-1)  # reducimos también el pivote a 1.
                A[k] = A[k]*piv^(-1)
                lista_transfos.append( ('rescale', (k+1, piv^(-1))) )
    print()
    ## Presentación de los resultados
    if ver_transfo:
        print('Matriz original:')
        print(M)
        print()
        print('Transformaciones elementales realizadas:')
        for (tipo, parametros) in lista_transfos:
            if tipo == 'swap':
                (indice1, indice2) = parametros
                #pretty_print(html('$F_{%s,%s}$'%(latex(indice1), latex(indice2))))
                pretty_print(html('$F_{%s} \\leftrightarrow F_{%s}$'%(latex(indice1), latex(indice2))))
                print()
            elif tipo == 'combination':
                (indice1, indice2, factor) = parametros
                #pretty_print(html('$F_{%s,%s}(%s)$'%(latex(indice1),latex(indice2), latex(factor))))
                pretty_print(html('$F_{%s}\\leftarrow F_{%s} + (%s) \\cdot F_{%s}$'
                                  %(latex(indice1),latex(indice1), latex(factor), latex(indice2))))
                print()
            elif tipo == 'rescale':
                (indice, factor) = parametros
                #pretty_print(html('$F_{%s}(%s)$'%(latex(indice), latex(factor))))
                pretty_print(html('$F_{%s} \\leftarrow %s\\cdot F_{%s}$'
                                  %(latex(indice), latex(factor), latex(indice))))
                print()
    if canon:
        print('Forma escalonada canónica:')
    else:
        print('Forma escalonada simple:')
    print(A)
    return(F, A)


<p>Retomando el ejemplo anterior, tenemos:</p>

In [59]:
A = matrix([[2, 1, 1/3], [-1, 6, 2], [1/2, 1, 8]])
b = vector([14/3, 2, -6])
M = A.augment(b.column())
show(M)

[   2    1  1/3 14/3]
[  -1    6    2    2]
[ 1/2    1    8   -6]

In [60]:
F, E = forma_escalonada(M, True, True)


Matriz original:
[   2    1  1/3 14/3]
[  -1    6    2    2]
[ 1/2    1    8   -6]

Transformaciones elementales realizadas:


<script type="math/tex">F_{2}\leftarrow F_{2} + (\frac{1}{2}) \cdot F_{1}</script>

<script type="math/tex">F_{3}\leftarrow F_{3} + (-\frac{1}{4}) \cdot F_{1}</script>

<script type="math/tex">F_{1} \leftarrow \frac{1}{2}\cdot F_{1}</script>

<script type="math/tex">F_{3}\leftarrow F_{3} + (-\frac{3}{26}) \cdot F_{2}</script>

<script type="math/tex">F_{1}\leftarrow F_{1} + (-\frac{1}{13}) \cdot F_{2}</script>

<script type="math/tex">F_{2} \leftarrow \frac{2}{13}\cdot F_{2}</script>

<script type="math/tex">F_{2}\leftarrow F_{2} + (-\frac{1}{23}) \cdot F_{3}</script>

<script type="math/tex">F_{3} \leftarrow \frac{3}{23}\cdot F_{3}</script>


Forma escalonada canónica:
[ 1  0  0  2]
[ 0  1  0  1]
[ 0  0  1 -1]


<p>Ahora comprobamos los resultados obtenidos:</p>

In [61]:
E

[ 1  0  0  2]
[ 0  1  0  1]
[ 0  0  1 -1]

In [62]:
F*M

[ 1  0  0  2]
[ 0  1  0  1]
[ 0  0  1 -1]

In [63]:
F*M == E

True

<p>Otras variantes:</p>

In [64]:
F, E = forma_escalonada(M)



Forma escalonada simple:
[    2     1   1/3  14/3]
[    0  13/2  13/6  13/3]
[    0     0  23/3 -23/3]


In [65]:
F, E = forma_escalonada(M, True)


Forma escalonada canónica:
[ 1  0  0  2]
[ 0  1  0  1]
[ 0  0  1 -1]


In [66]:
F, E = forma_escalonada(M, False, True)


Matriz original:
[   2    1  1/3 14/3]
[  -1    6    2    2]
[ 1/2    1    8   -6]

Transformaciones elementales realizadas:


<script type="math/tex">F_{2}\leftarrow F_{2} + (\frac{1}{2}) \cdot F_{1}</script>

<script type="math/tex">F_{3}\leftarrow F_{3} + (-\frac{1}{4}) \cdot F_{1}</script>

<script type="math/tex">F_{3}\leftarrow F_{3} + (-\frac{3}{26}) \cdot F_{2}</script>


Forma escalonada simple:
[    2     1   1/3  14/3]
[    0  13/2  13/6  13/3]
[    0     0  23/3 -23/3]


<h3>Cálculo de las soluciones de un sistema de ecuaciones</h3>
<p>A modo de ejemplo, aplicaremos el método de escalonamiento para hallar todas las posibles soluciones del sistema lineal</p>
<p>
$$\left\lbrace \begin{array}{rcl} x+2y-z&=& 3\\ 2x-3y+2z&=&-1\\  3x-y+z&=&2\end{array}\right. $$
</p>

In [67]:
M = matrix(QQ,[[1,2,-1,3],[2,-3,2,-1],[3,-1,1,2]])
show(M)

[ 1  2 -1  3]
[ 2 -3  2 -1]
[ 3 -1  1  2]

In [68]:
F, U = forma_escalonada(M, True, False)


Forma escalonada canónica:
[   1    0  1/7    1]
[   0    1 -4/7    1]
[   0    0    0    0]


Del resultado obtenido se deduce que podemos tomar como variables dependientes:$x,y$ y como variable independiente:$z$. El sistema tiene infinitas soluciones que pueden expresarse, en función de un parámetro $\alpha$, como:
$$\left\lbrace \begin{array}{rcl} x&=& 1-\frac 17 \alpha\\ y&=&1+\frac 47 \alpha\\  z&=&\alpha\end{array}\right. $$

<h3>Cálculo de la matriz inversa por el método de Gaus-Jordan</h3>
<p>Recrearemos el método de Gauss-Jordan para hallar la inversa de una matriz $A$:</p>

In [69]:
A = matrix(QQ, [[0, 1, -2], [4, 1, 0], [2, 1, 1]])
show(A)

[ 0  1 -2]
[ 4  1  0]
[ 2  1  1]

<p>Construimos la matriz de dos bloques $(A|I)$:</p>

In [70]:
M = block_matrix([[A, identity_matrix(base_ring(A), A.nrows())]])
show(M)

[ 0  1 -2| 1  0  0]
[ 4  1  0| 0  1  0]
[ 2  1  1| 0  0  1]

<p>Aplicamos el método de Gauss-Jordan a esta matriz doble:</p>

In [71]:
F, U = forma_escalonada(M, True, True)


Matriz original:
[ 0  1 -2| 1  0  0]
[ 4  1  0| 0  1  0]
[ 2  1  1| 0  0  1]

Transformaciones elementales realizadas:


<script type="math/tex">F_{1} \leftrightarrow F_{2}</script>

<script type="math/tex">F_{3}\leftarrow F_{3} + (-\frac{1}{2}) \cdot F_{1}</script>

<script type="math/tex">F_{1} \leftarrow \frac{1}{4}\cdot F_{1}</script>

<script type="math/tex">F_{3}\leftarrow F_{3} + (-\frac{1}{2}) \cdot F_{2}</script>

<script type="math/tex">F_{1}\leftarrow F_{1} + (-\frac{1}{4}) \cdot F_{2}</script>

<script type="math/tex">F_{2} \leftarrow 1\cdot F_{2}</script>

<script type="math/tex">F_{1}\leftarrow F_{1} + (-\frac{1}{4}) \cdot F_{3}</script>

<script type="math/tex">F_{2}\leftarrow F_{2} + (1) \cdot F_{3}</script>

<script type="math/tex">F_{3} \leftarrow \frac{1}{2}\cdot F_{3}</script>


Forma escalonada canónica:
[   1    0    0|-1/8  3/8 -1/4]
[   0    1    0| 1/2 -1/2    1]
[   0    0    1|-1/4 -1/4  1/2]


La matriz inversa de $A$ es el bloque de la derecha de la matriz $U$ obtenida.

In [72]:
U

[   1    0    0|-1/8  3/8 -1/4]
[   0    1    0| 1/2 -1/2    1]
[   0    0    1|-1/4 -1/4  1/2]

In [73]:
U.matrix_from_columns([3,4,5])

[-1/8  3/8 -1/4]
[ 1/2 -1/2    1]
[-1/4 -1/4  1/2]

<h2><a name="anillos"></a>Trabajando con diferentes dominios (anillos) de números</h2>
<p>En SageMath se declaran lo que se conoce como *clases* de objetos y, en el caso de manipulaciones numéricas, están declaradas las clases <span style="color: #0000ff;">ZZ</span>, <span style="color: #0000ff;">QQ</span>, <span style="color: #0000ff;">RR</span> y <span style="color: #0000ff;">CC</span> para representar los anillos de los números enteros, racionales, reales y complejos, respectivamente. Cuando una función actúa sobre un objeto, su comportamiento puede depender de la clase a la que pertenezca el objeto. Es decir, SageMath respeta en todos sus procedimientos, por defecto, el tipo de datos declarados en la entrada y acomoda sus cálculos y funciones a esos tipos. Particularmente interesante puede resultar trabajar sobre el anillo $Z_n$ de los enteros modulo $n$ (https://es.wikipedia.org/wiki/Aritmética_modular) (ver también la asignatura de I.M.D.) y que podemos declarar con la clase <span style="color: #0000ff;">IntegerModRing(n)</span>.<br /><br /><br /></p>
<h3>Ejemplo 2:</h3>
<p>A continuación declaramos una matriz de números racionales y comprobamos que su  inversa dentro de ese dominio es tratada diferente que en otros dominios como los reales o $Z_n$.</p>

In [74]:
A = matrix(QQ, [[2, 1, 4], [1, 6, 3], [1, 1, 8]])
show(A)
Ai = A.inverse()
show(Ai)

[2 1 4]
[1 6 3]
[1 1 8]

[  9/13  -4/65 -21/65]
[ -1/13  12/65  -2/65]
[ -1/13  -1/65  11/65]

In [75]:
show(A*Ai)

[1 0 0]
[0 1 0]
[0 0 1]

<p>Cambiamos de clase o dominio al de los números reales (en realidad son números en punto flotante con 16 dígitos de presición, por defecto):</p>

In [76]:
B = A.change_ring(RR)
show(B)


[2.00000000000000 1.00000000000000 4.00000000000000]
[1.00000000000000 6.00000000000000 3.00000000000000]
[1.00000000000000 1.00000000000000 8.00000000000000]

In [77]:
Bi = B.inverse();
show(Bi)


[  0.692307692307692 -0.0615384615384615  -0.323076923076923]
[-0.0769230769230769   0.184615384615385 -0.0307692307692308]
[-0.0769230769230769 -0.0153846153846154   0.169230769230769]

In [78]:
show(B*Bi) # debe dar la matriz identidad ... aproximadamente.

[     1.00000000000000     0.000000000000000     0.000000000000000]
[-5.55111512312578e-17      1.00000000000000     0.000000000000000]
[    0.000000000000000     0.000000000000000      1.00000000000000]

<p>Por defecto, SageMath trabaja con una precisión numérica en el caso de números en formato de coma flotante correspondiente a 53 bits en la mantisa.  Podemos elegir otra precisión diferente. Por ejemplo, vamos a limitar la precisión a 12 bits en la mantisa:</p>

In [79]:
B = A.change_ring(RealField(12)) # creamos una copia con menor precisión numérica
show(B)

[2.00 1.00 4.00]
[1.00 6.00 3.00]
[1.00 1.00 8.00]

In [80]:
Bi = B.inverse();
show(Bi)

[  0.692 -0.0615  -0.323]
[-0.0769   0.185 -0.0308]
[-0.0769 -0.0154   0.169]

In [81]:
show(B*Bi) # como consecuencia de la menor precisión ,obtenemos un mayor error en nuestros cálculos

[     1.00 0.0000305     0.000]
[-0.000122      1.00     0.000]
[    0.000     0.000      1.00]

<p>Ahora pasemos al anillo $Z_6$ de los números enteros módulo 6:</p>

In [82]:
show(A)
C = A.change_ring(IntegerModRing(6))
show(C)

[2 1 4]
[1 6 3]
[1 1 8]

[2 1 4]
[1 0 3]
[1 1 2]

In [83]:
Ci = C.inverse(); # El cálculo se hace con los enteros módulo 6.
show(Ci)

[3 4 3]
[5 0 2]
[5 1 1]

In [84]:
show(C*Ci) # Son cálculos exactos.

[1 0 0]
[0 1 0]
[0 0 1]

<h2><a name="aplicaciones"></a>Algunas aplicaciones prácticas</h2>
<p>Estudiamos algunos ejemplos de problemas reales cuyo planteamiento y posterior resolución puede conseguirse mediante sistemas de ecuaciones lineales.</p>

<h3>Optimización del tráfico en una red</h3>
<p>Se pretende averiguar cuál es la mejor forma de distribuir un flujo o tráfico dado de vehículos en cierta zona de una ciudad. Más concretamente, considérese la red de tráfico dada en el siguiente dibujo:</p>
<p><img src="network.jpg" alt="" /></p>
<p>En esta red, las letras {A, B,...,F} representan cruces o intersecciones de calles, las flechas indican la dirección en la que circulan los vehículos y los números la cantidad media de vehículos que surcan las calles en las horas punta, medidos en los puntos de entrada y salida a esa zona. Por otra parte, las variables $\{t, u, v,\dots, z\}$ representan el reparto ideal del flujo de tráfico por cada calle. Se pide:</p>
<p>a) Encontrar una relación entre las variables que permita distribuir de manera óptima el tráfico en hora punta.</p>
<p>b) En caso de que las calles de $A$ a $B$ y de $B$ a $C$ deban cerrarse al tráfico por algún motivo, ¿cómo debería reorganizarse el tráfico?</p>
<h4>Solución:</h4>
<p>a) El problema se puede modelar mediante un sistema lineal de ecuaciones, asumiendo que en hora punta el flujo que entra en un vértice coincide con el flujo que sale del mismo. Así, asumiendo la notación del dibujo anterior, y traduciendo las ecuaciones que corresponden a los vértices $A,B,C,D,E,F$, tenemos el sistema</p>
$$\left\lbrace \begin{array}{rcl} 800&=& x+v\\ u+x&=&y+400\\ y&=&z+600\\ 1600+z&=&t+400\\ t&=&u+w\\ v+w&=&1000\end{array}\right. $$
que se escribe de forma matricial como
$$\left[ \begin{array}{rrrrrrr} 0&0&1&0&1&0&0\\ 0&1&0&0&1&-1&0\\ 0&0&0&0&0&1&-1\\ -1&0&0&0&0&0&1\\ -1&1&0&1&0&0&0\\ 0&0&1&1&0&0&0 \end{array} \right]\left[ \begin{array}{c}t\\ u\\v\\w\\x\\y\\z \end{array}\right]= \left[ \begin{array}{r} 800\\ 400 \\ 600 \\ -1200\\ 0 \\ 1000 \end{array}\right]$$

In [85]:
A = matrix(QQ,
[
[0, 0, 1, 0, 1, 0, 0, 800],
[0, 1, 0, 0, 1, -1, 0, 400],
[0, 0, 0, 0, 0, 1, -1, 600],
[-1, 0, 0, 0, 0, 0, 1, -1200],
[-1, 1, 0, 1, 0, 0, 0, 0],
[0, 0, 1, 1, 0, 0, 0, 1000]
])
show(A)

[    0     0     1     0     1     0     0   800]
[    0     1     0     0     1    -1     0   400]
[    0     0     0     0     0     1    -1   600]
[   -1     0     0     0     0     0     1 -1200]
[   -1     1     0     1     0     0     0     0]
[    0     0     1     1     0     0     0  1000]

In [4]:
A = matrix(QQ,
[
[1, -1, 0, 0, 0, 0, -1],
[0, -1/2, 1, 0, 0, 0, 0],
[0, 0, -3, 1, 0, 0, 0],
[0, 0, 0, -1, 9, 10, 0],
[1, 1, 1, 1, 1, 1, 24]
])
show(A)

[   1   -1    0    0    0    0   -1]
[   0 -1/2    1    0    0    0    0]
[   0    0   -3    1    0    0    0]
[   0    0    0   -1    9   10    0]
[   1    1    1    1    1    1   24]

In [5]:
F, U = forma_escalonada(A, True)


Forma escalonada canónica:
[    1     0     0     0     0 -2/75     5]
[    0     1     0     0     0 -2/75     6]
[    0     0     1     0     0 -1/75     3]
[    0     0     0     1     0 -1/25     9]
[    0     0     0     0     1 83/75     1]


<p>Resolvemos el sistema llevándolo a su forma escalonada reducida:</p>

In [86]:
F, U = forma_escalonada(A, True)


Forma escalonada canónica:
[   1    0    0    0    0    0   -1 1200]
[   0    1    0    0    1    0   -1 1000]
[   0    0    1    0    1    0    0  800]
[   0    0    0    1   -1    0    0  200]
[   0    0    0    0    0    1   -1  600]
[   0    0    0    0    0    0    0    0]


<p>Tomando como variables dependientes las asociadas a los pivotes, tenemos variables independientes $x$ y $z$. Expresamos así las relaciones entre todas las variables:</p>
<p>$$t=z+1200,\ u=z-x+1000,\ v=800-x,\ w=x+200,\ y=z+600$$</p>
<p>b) La ausencia de tráfico entre los cruces A y B y entre B y C se expresan con  $x=y=0$. En particular, de $y=0$ se tiene que $z=-600$. Finalmente resulta:</p>
<p>$$t=600, \ u=400, \ v=800, \ w=200$$</p>
<p>El valor negativo $z=-600$ indica que se tendría que cambiar el sentido de la calle entre C y D.</p>

<h3>Atacando criptosistemas afines</h3>
<p>En la antigüedad, una forma de encriptar mensajes consistía en asignar un número $x$ a cada elemento de un alfabeto de longitud $n$, tal como se muestra en la siguiente tabla (alfabeto de 29 caracteres, donde el caracter "Ñ" se ha sustituido por "-" para evitar problemas con caracteres especiales) y posteriormente transformar dicho número en otro diferente $y=ax+b$.</p>
<p>Para que los valores transformados sean también números de la tabla y por tanto se correspondan con letras, basta trabajar con el anillo $Z_{29}$ de los enteros modulares y tomar  el parámetro $a$ y el parámetro $b$ cualesquiera números entre 0 y 28, por ser 29 un número primo; en caso contrario, debería ser el parámetro $a$ coprimo con $n$. Tales sistemas de encriptación se conocen como criptosistemas afines y como veremos a continuación son relativamente sencillos de romper, esto es, desencriptar si se dispone de un poco de información. No obstante fueron utilizados hasta finales del siglo XV.</p>
<p> </p>
<table border="0" cellspacing="0"><colgroup span="13" width="59"></colgroup>
<tbody>
<tr>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC" height="20"><span style="font-family: DejaVu Sans;">A</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">B</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">C</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">D</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">E</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">F</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">G</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">H</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">I</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">J</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">K</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">L</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">M</span></td>
</tr>
<tr>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" height="20"><span style="font-family: DejaVu Sans;">0</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">1</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">2</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">3</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">4</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">5</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">6</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">7</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">8</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">9</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">10</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">11</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">12</span></td>
</tr>
<tr>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC" height="20"><span style="font-family: DejaVu Sans;">N</span></td>
<td style="border: 1px solid #000000;" align="CENTER" bgcolor="#CCCCCC">-</td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">O</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">P</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">Q</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">R</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">S</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">T</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">U</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">V</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">W</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">X</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">Y</span></td>
</tr>
<tr>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP" height="20"><span style="font-family: DejaVu Sans;">13</span></td>
<td style="border: 1px solid #000000;" align="CENTER"><span style="font-family: DejaVu Sans;">14</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">15</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">16</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">17</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">18</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">19</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">20</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">21</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">22</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">23</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">24</span></td>
<td style="border: 1px solid #000000;" align="CENTER" valign="TOP"><span style="font-family: DejaVu Sans;">25</span></td>
</tr>
<tr>
<td style="border: 1px solid #000000;" align="CENTER" bgcolor="#CCCCCC" height="19"><span style="font-family: DejaVu Sans;">Z</span></td>
<td style="border: 1px solid #000000;" align="CENTER" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">.</span></td>
<td style="border: 1px solid #000000;" align="CENTER" bgcolor="#CCCCCC"><span style="font-family: DejaVu Sans;">_<br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
</tr>
<tr>
<td style="border: 1px solid #000000;" align="CENTER" height="19"><span style="font-family: DejaVu Sans;">26</span></td>
<td style="border: 1px solid #000000;" align="CENTER"><span style="font-family: DejaVu Sans;">27</span></td>
<td style="border: 1px solid #000000;" align="CENTER"><span style="font-family: DejaVu Sans;">28</span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"><span style="font-family: DejaVu Sans;"><br /></span></td>
<td align="CENTER"> </td>
</tr>
</tbody>
</table>
<p> </p>
<p>Para descifrar cada letra, basta tomar $x=a^{-1} (y-b)$. De ahí la importancia de que $a$ sea coprimo con $n$, para garantizar que existe su inverso modular.</p>
<p>a) Descifrar el texto "NSM-YT.E", sabiendo que la "E" se codifica como  "." y la "N" se codifica como una  "E".</p>
<p>b) Una versión más moderna es el  <b>cifrado de Hill </b>, que usa la versión matricial de las ecuaciones anteriores: $y=Ax+b$, $x=A^{-1}(y-b)$. Descifrar el texto "P.SPGZOHF", sabiendo que se ha usado una matriz $A$ de orden $3$, y que los cifrados de "SECRET" y "MYCODE" son, respectivamente, "QACNQN" y "OQCTZJ". Deducir que la versión matricial no aporta realmente ninguna seguridad al método clásico, salvo  un incremento del  cálculo necesario, fácilmente computable con un ordenador.</p>
<h4>Solución:</h4>
<p>a) Planteamos el sistema de ecuaciones a partir de la información disponible $y_i=ax_i+b$ en las incógnitas $\{ a, b\}$. Una vez obtenida la solución al sistema, podemos decodificar el mensaje  utilizando $x_i=a^{-1}y_i-a^{-1}b$.  Si denotamos $A=a^{-1}$, y $B=a^{-1}b$, resulta $x_i=Ay_i-B$.</p>
<p>Sustituyendo los valores conocidos, tenemos el sistema:</p>
<p>$\left.\begin{array}{rcr} 27&=&4a &+b\\4&=&13a &+b  \end{array}\right\}$</p>
<p>La matriz ampliada del sistema es</p>

In [87]:
M = matrix(IntegerModRing(29), [[4, 1, 27], [13, 1, 4]])
show(M)


[ 4  1 27]
[13  1  4]

<p>Ahora resolvemos el sistema mediante escalonamiento:</p>

In [88]:
F, U = forma_escalonada(M, True)


Forma escalonada canónica:
[ 1  0 20]
[ 0  1  5]


<p>Ha resultado la siguiente solución:</p>
<p>$a=20\mod(29),\ b=5\mod(29)$</p>
<p>A continuación procedemos a decodificar el mensaje:</p>

In [89]:
a = mod(20, 29); b = mod(5, 29)
A = a^-1; B = a^-1*b
(A, B)


(16, 22)

In [21]:
alfabeto = "ABCDEFGHIJKLMN-OPQRSTUVWXYZ._"

In [91]:
mensaje_codificado = "NSM-YT.E"

In [92]:
cifrado_mensaje = [alfabeto.index(i) for i in mensaje_codificado]
cifrado_mensaje

[13, 19, 12, 14, 25, 20, 27, 4]

In [93]:
descifrado_mensaje = [A*mod(y, 29) - B for y in cifrado_mensaje]
descifrado_mensaje

[12, 21, 25, 28, 1, 8, 4, 13]

In [94]:
mensaje_original=""
for i in descifrado_mensaje:
    mensaje_original = mensaje_original + alfabeto[i]

mensaje_original

'MUY_BIEN'

<p>b) Llamemos $A=\left( \begin{array}{ccc} a_{11}&a_{12}&a_{13}\\ a_{21}&a_{22}&a_{23}\\ a_{31}&a_{32}&a_{33}\end{array} \right)$ y ${\bf b}= \left( \begin{array}{c}b_1\\b_2\\b_3 \end{array}\right)$</p>
<p>Si sustituimos en la ecuación ${\bf y}=A{\bf x}+{\bf b}$ la información del enunciado relativa a los dos mensajes conocidos, tomando cadenas de longitud tres, y dados los siguientes valores numéricos asociados a las letras implicadas:</p>

In [95]:
pistas = "SECRET"+"MYCODE"
cifrado_pistas = [alfabeto.index(i) for i in pistas]
cifrado_pistas

[19, 4, 2, 18, 4, 20, 12, 25, 2, 15, 3, 4]

In [96]:
pistas_codificadas = "QACNQN"+"OQCTZJ"
cifrado_pistas_codificadas = [alfabeto.index(i) for i in pistas_codificadas]
cifrado_pistas_codificadas

[17, 0, 2, 13, 17, 13, 15, 17, 2, 20, 26, 9]

<p>se obtiene el sistema:</p>
$$\left.\begin{matrix}
19a_{11}&+ 4a_{12}&+ 2a_{13}& & & & & & &+ b_1& & &=&17 \\
& & & 19a_{21}&+ 4a_{22}&+ 2a_{23}& & & & &+ b_2& &=&0 \\
& & & & & & 19a_{31}&+ 4a_{32}&+ 2a_{33}& & &+ b_3&=&2 \\
18a_{11}&+ 4a_{12}&+ 20a_{13}& & & & & & &+ b_1& & &=&13 \\
& & & 18a_{21}&+ 4a_{22}&+ 20a_{23}& & & & &+ b_2& &=&17 \\
& & & & & & 18a_{31}&+ 4a_{32}&+ 20a_{33}& & &+ b_3&=&13\\
12a_{11}&+ 25a_{12}&+ 2a_{13}& & & & & & &+ b_1& & &=&15 \\
& & & 12a_{21}&+ 25a_{22}&+ 2a_{23}& & & & &+ b_2& &=&17 \\
& & & & & & 12a_{31}&+ 25a_{32}&+ 2a_{33}& & &+ b_3&=&2\\
15a_{11}&+ 3a_{12}&+ 4a_{13}& & & & & & &+ b_1& & &=&20 \\
& & & 15a_{21}&+ 3a_{22}&+ 4a_{23}& & & & &+ b_2& &=&26 \\
& & & & & & 15a_{31}&+ 3a_{32}&+ 4a_{33}& & &+ b_3&=&9
\end{matrix}\right\rbrace$$
<p> Creamos la matriz ampliada de dicho sistema:</p>

In [97]:
M = matrix(IntegerModRing(29),
[
[19, 4, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 19, 4, 2, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 19, 4, 2, 0, 0, 1],
[18, 4, 20, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 18, 4, 20, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 18, 4, 20, 0, 0, 1],
[12, 25, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 12, 25, 2, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 12, 25, 2, 0, 0, 1],
[15, 3, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 15, 3, 4, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 15, 3, 4, 0, 0, 1]
]).augment(column_matrix(IntegerModRing(29),cifrado_pistas_codificadas))
show(M)

[19  4  2  0  0  0  0  0  0  1  0  0 17]
[ 0  0  0 19  4  2  0  0  0  0  1  0  0]
[ 0  0  0  0  0  0 19  4  2  0  0  1  2]
[18  4 20  0  0  0  0  0  0  1  0  0 13]
[ 0  0  0 18  4 20  0  0  0  0  1  0 17]
[ 0  0  0  0  0  0 18  4 20  0  0  1 13]
[12 25  2  0  0  0  0  0  0  1  0  0 15]
[ 0  0  0 12 25  2  0  0  0  0  1  0 17]
[ 0  0  0  0  0  0 12 25  2  0  0  1  2]
[15  3  4  0  0  0  0  0  0  1  0  0 20]
[ 0  0  0 15  3  4  0  0  0  0  1  0 26]
[ 0  0  0  0  0  0 15  3  4  0  0  1  9]

<p>Ahora intentamos resolver el sistema mediante escalonamiento:</p>

In [98]:
F, U = forma_escalonada(M, True)


Forma escalonada canónica:
[ 1  0  0  0  0  0  0  0  0  0  0  0 10]
[ 0  1  0  0  0  0  0  0  0  0  0  0  6]
[ 0  0  1  0  0  0  0  0  0  0  0  0 10]
[ 0  0  0  1  0  0  0  0  0  0  0  0  5]
[ 0  0  0  0  1  0  0  0  0  0  0  0  8]
[ 0  0  0  0  0  1  0  0  0  0  0  0 27]
[ 0  0  0  0  0  0  1  0  0  0  0  0 20]
[ 0  0  0  0  0  0  0  1  0  0  0  0 26]
[ 0  0  0  0  0  0  0  0  1  0  0  0 13]
[ 0  0  0  0  0  0  0  0  0  1  0  0 15]
[ 0  0  0  0  0  0  0  0  0  0  1  0 22]
[ 0  0  0  0  0  0  0  0  0  0  0  1 14]


<p>Construimos la matriz $A$ y el vector $b$ soluciones del sistema anterior:</p>

In [99]:
A = matrix(IntegerModRing(29), 3, 3, list(U.column(12)[0:9]))
show(A)
b = vector(IntegerModRing(29), list(U.column(12)[9:]))
show(b)

[10  6 10]
[ 5  8 27]
[20 26 13]

(15, 22, 14)

In [100]:
Ai = A.inverse()
show(Ai)

[24 28 26]
[24 16 13]
[11  3  1]

<p>Ahora ya tenemos todos los cálculos requeridos para poder desencriptar el código proporcionado:</p>

In [101]:
mensaje_codificado = "P.SPGZOHF"

In [102]:
cifrado_mensaje = [alfabeto.index(i) for i in mensaje_codificado]
cifrado_mensaje

[16, 27, 19, 16, 6, 26, 15, 7, 5]

<p>Ahora ya podemos descifrar el texto "P.SPGZOHF", que es la suma de las cadenas "P.S" , "PGZ" y "OHF", las cuales se corresponden, según el alfabeto, con los vectores</p>
<p>$y_1=(16,27,19)$ , $y_2=(16,6,26)$, $y_3=(15,7,5)$</p>
<p>Los correspondientes $x_i=A^{-1}(y_i-b)$ se obtienen a continuación:</p>

In [103]:
x1 = list(Ai*(vector(IntegerModRing(29),cifrado_mensaje[0:3])-b))
x1


[4, 24, 2]

In [104]:
x2 = list(Ai*(vector(IntegerModRing(29),cifrado_mensaje[3:6])-b))
x2

[4, 11, 4]

In [105]:
x3 = list(Ai*(vector(IntegerModRing(29),cifrado_mensaje[6:9])-b))
x3

[13, 20, 4]

In [106]:
descifrado_mensaje = x1 + x2 + x3
descifrado_mensaje

[4, 24, 2, 4, 11, 4, 13, 20, 4]

In [107]:
mensaje_original = ""
for i in descifrado_mensaje:
    mensaje_original = mensaje_original + alfabeto[i]

mensaje_original

'EXCELENTE'

<h3> </h3>
<h2>Construcción de cuadrados mágicos</h2>
<p>Un cuadrado mágico de tamaño $n$ consiste en una matriz cuadrada de orden $n$ cuyas entradas son todos los enteros desde 1 hasta $n^2$, con la propiedad adicional de que la suma de cada fila, columna o diagonal es la misma constante.</p>
<p>De la fórmula</p>
<p>$$1+2+3+\cdots + N=\frac{N(N+1)}{2}$$</p>
<p>aplicada con $N=n^2$, deducimos que la suma de todas las entradas de un cuadrado mágico de tamaño $n$ debe ser $\frac{n^2(n^2+1)}{2}$.Como las $n$ filas deben sumar igual, cada fila debe tener como suma el número anterior dividido entre $n$, o sea: $\frac{n(n^2+1)}{2}$.</p>
<p>Considérese el caso de $n=2$,</p>

<table border="1" cellpadding="2">
<tbody>
<tr>
<td>a</td>
<td>b</td>
</tr>
<tr>
<td>c</td>
<td>d</td>
</tr>
</tbody>
</table>

<p>Para que los parámetros den un cuadrado mágico, además de ser los números 1,2,3,4, deben satisfacer el siguiente sistema de ecuaciones:</p>
$$\left\lbrace \begin{eqnarray}a + b &=5 \\c + d & = 5 \\ a+c &=5 \\ b+ d &= 5 \\ a+d &=5 \\ b + c &=5\end{eqnarray}\right.$$
<p>Para el caso $n=3$, un cuadrado mágico genérico tendría la forma</p>
<table border="1" cellpadding="2">
<tbody>
<tr>
<td>a</td>
<td>b</td>
<td>c</td>
</tr>
<tr>
<td>d</td>
<td>e</td>
<td>f</td>
</tr>
<tr>
<td>g</td>
<td>h</td>
<td>i</td>
</tr>
</tbody>
</table>
<p>En este caso, se tendría que satisfacer el sistema de ecuaciones siguiente:</p>
$$\left\lbrace \begin{eqnarray}a+b+c = 15\\d +e +f = 15\\g + h + i = 15\\a  + d + g = 15\\b + e + h = 15\\c + f + i = 15\\a + e + i = 15\\c + e + g = 15\\\end{eqnarray}\right.$$
<p> </p>
<p>Se pide:</p>
<p>a) Mediante transformaciones elementales por filas, encontrar la solución del sistema para $n=2$. Deducir que no existen cuadrados mágicos para $n=2$.</p>
<p>b) Encontrar la solución general del sistema para el caso $n=3$. Dar explícitamente un cuadrado mágico que sea solución particular del sistema.</p>
<h4>Solución:</h4>
<p>a) Montamos el sistema correspondiente al cuadrado mágico de orden 2</p>

In [108]:
A = matrix(QQ, [
[1, 1, 0, 0, 5],
[0, 0, 1, 1, 5],
[1, 0, 1, 0, 5],
[0, 1, 0, 1, 5],
[1, 0, 0, 1, 5],
[0, 1, 1, 0, 5]
])
show(A)

[1 1 0 0 5]
[0 0 1 1 5]
[1 0 1 0 5]
[0 1 0 1 5]
[1 0 0 1 5]
[0 1 1 0 5]

In [109]:
F, U = forma_escalonada(A, True)


Forma escalonada canónica:
[  1   0   0   0 5/2]
[  0   1   0   0 5/2]
[  0   0   1   0 5/2]
[  0   0   0   1 5/2]
[  0   0   0   0   0]
[  0   0   0   0   0]


<p>De donde este sistema tiene un a única solución: $a=5/2, b=5/2, c=5/2, d=5/2$, pero no es formada por enteros. Por tanto no existen cuadrados mágicos de orden 2.</p>
<p>b) El sistema correspondiente a cuadrados mágicos de orden 3 es:</p>

In [110]:
A = matrix(QQ,
[
[1, 1, 1, 0, 0, 0, 0, 0, 0, 15],
[0, 0, 0, 1, 1, 1, 0, 0, 0, 15],
[0, 0, 0, 0, 0, 0, 1, 1, 1, 15],
[1, 0, 0, 1, 0, 0, 1, 0, 0, 15],
[0, 1, 0, 0, 1, 0, 0, 1, 0, 15],
[0, 0, 1, 0, 0, 1, 0, 0, 1, 15],
[1, 0, 0, 0, 1, 0, 0, 0, 1, 15],
[0, 0, 1, 0, 1, 0, 1, 0, 0, 15]
])
show(A)

[ 1  1  1  0  0  0  0  0  0 15]
[ 0  0  0  1  1  1  0  0  0 15]
[ 0  0  0  0  0  0  1  1  1 15]
[ 1  0  0  1  0  0  1  0  0 15]
[ 0  1  0  0  1  0  0  1  0 15]
[ 0  0  1  0  0  1  0  0  1 15]
[ 1  0  0  0  1  0  0  0  1 15]
[ 0  0  1  0  1  0  1  0  0 15]

In [111]:
F, U = forma_escalonada(A, True)


Forma escalonada canónica:
[  1   0   0   0   0   0   0   0   1  10]
[  0   1   0   0   0   0   0   1   0  10]
[  0   0   1   0   0   0   0  -1  -1  -5]
[  0   0   0   1   0   0   0  -1  -2 -10]
[  0   0   0   0   1   0   0   0   0   5]
[  0   0   0   0   0   1   0   1   2  20]
[  0   0   0   0   0   0   1   1   1  15]
[  0   0   0   0   0   0   0   0   0   0]


<p>El sistema es equivalente a</p>
$$\begin{align}a&=10-i,\\ b&=10-h,\\ c&=h+i-5,\\ d&=h+2i-10,\\ e&=5,\\ f&=20-h-2i,\\ g&=15-h-i\end{align}$$
<p>Además $h$ e $i$ deben ser enteros distintos, entre $1$ y $9$. Podemos listar las 56 posibilidades (81 parejas $(h,i)$ con $1 \leq h,i \leq 9$, menos las parejas del tipo $(k,k)$ con dos entradas iguales, $1 \leq k \leq 9$, menos 8 entradas del tipo $(5,\ast)$, menos 8 entradas del tipo $(\ast,5)$), y descartar de entre ellas aquellas en las que las variables $a,b,c,d,e,f,g,h,i$ no tomen el abanico completo de valores comprendidos entre $1$ y $9$.</p>

In [112]:
for h in [1, 2, 3, 4, 6, 7, 8, 9]:
    for i in [1, 2, 3, 4, 6, 7, 8, 9]:
        if h != i:
            S = set([10 - i, 10 - h, h + i - 5, h + 2*i - 10, 5, 20 - h - 2*i, 15 - h - i, h, i])
            if S == set([1, 2, 3, 4, 5, 6, 7, 8, 9]):
                print("Encontrada solución para el par (h, i): (h,i) = (%d,%d)."%(h,i))

Encontrada solución para el par (h, i): (h,i) = (1,6).
Encontrada solución para el par (h, i): (h,i) = (1,8).
Encontrada solución para el par (h, i): (h,i) = (3,4).
Encontrada solución para el par (h, i): (h,i) = (3,8).
Encontrada solución para el par (h, i): (h,i) = (7,2).
Encontrada solución para el par (h, i): (h,i) = (7,6).
Encontrada solución para el par (h, i): (h,i) = (9,2).
Encontrada solución para el par (h, i): (h,i) = (9,4).


<p>Por ejemplo, tomemos el par $(h,i)=(1,6)$, y resulta la matriz con valores:</p>

In [113]:
h = 1; i = 6
valores = [10 - i, 10 - h, h + i - 5, h + 2*i - 10, 5, 20 - h - 2*i, 15 - h - i, h, i]
valores

[4, 9, 2, 3, 5, 7, 8, 1, 6]

In [114]:
cuadrado_magico_3 = matrix(3,valores)
show(cuadrado_magico_3)

[4 9 2]
[3 5 7]
[8 1 6]

<h3><a name="cuestionario"></a></h3>
<h3>CUESTIONARIO PARA EL ALUMNADO</h3>
<p><span id="cell_outer_0">Asigna a la variable NUMERO_CUESTIONARIO, que aparece más abajo, el número correspondiente a tu cuestionario y ejecuta la celda (*Shift* + *Enter* desde dentro de la celda). Accederás a un cuestionario con respuestas tipo test que se entregarán antes de finalizar esta sesión práctica, siguiendo las instrucciones del profesorado.</span></p>

In [2]:
NUMERO_CUESTIONARIO = 167    ## introducir el número asignado durante la práctica, entre 1 y 200

## no modificar el código de abajo
NOMBRE_FICHERO_EXAMEN = 'ALN_L1_t.htl'
load('codigo_examinar_html.sage')

if NUMERO_CUESTIONARIO>0:
    lector_examenes(NOMBRE_FICHERO_EXAMEN,NUMERO_CUESTIONARIO,False)

<center><h4>E.T.S.I.I. - GRADOS EN INGENIERÍA INFORMÁTICA</h4></center><center><h4>Álgebra Lineal y Numérica - PRIMERA PRÁCTICA DE LABORATORIO</h4></center><hr  align=center><center>APELLIDOS, NOMBRE: <INPUT value= "",type=text size=70> <INPUT type=submit value=167-64375><hr  align=center></center><hr  align=center><b> <span style="color: #0000ff;">EJERCICIO 1 </span></b><br> Sean las matrices <script type="math/tex; mode=display">A=\left(\begin{array}{rrr} -1 & 1 & \frac{1}{4} \\ 2 & 1 & 0 \\ 3 & 0 & -\frac{1}{4}\end{array}\right)\quad S=\left(\begin{array}{rrr} 3 & 1 & 0 \\ 6 & 2 & 1 \\ -1 & -\frac{1}{3} & 2\end{array}\right)</script>
 y vectores <script type="math/tex; mode=display">b=\left(\begin{array}{r} 0 \\ 3 \\ 3\end{array}\right)\quad t=\left(\begin{array}{r} 3 \\ 5 \\ -3\end{array}\right)</script> Se pide:<ol><li>Calcular <script type="math/tex">(S-S^t)^2</script>.</li><li>Estudiar el rango de las matrices <script type="math/tex">B=(A-A^t)^2</script> y <script type="math/tex">C=(S+S^t)^2</script>.</li><li>Hallar el conjunto de soluciones del sistema de ecuaciones lineales <script type="math/tex">Ax=b</script>.</li><li>Hallar el conjunto de soluciones del sistema de ecuaciones lineales <script type="math/tex">Sx=b</script>.</li><li>Hallar el conjunto de soluciones del sistema de ecuaciones lineales <script type="math/tex">Sx=t</script>.</li></ol>Marcar la respuesta correcta.<br><hr  align=center><b> <span style="color: #ff0000;">Respuesta al apartado 1 </span></b><br><br> <table style=" width:100%"> <tr> <td style="border:none; text-align:left">1.<input type=checkbox> <script type="math/tex">\left(\begin{array}{rrr} -\frac{41}{4} & 0 & 0 \\ 0 & -4 & -5 \\ 0 & -5 & -\frac{25}{4}\end{array}\right)</script>    </td> <td style="border:none; text-align:left">2.<input type=checkbox> <script type="math/tex">\left(\begin{array}{rrr} -26 & -\frac{4}{3} & -\frac{20}{3} \\ -\frac{4}{3} & -\frac{241}{9} & 5 \\ -\frac{20}{3} & 5 & -\frac{25}{9}\end{array}\right)</script>    </td> </tr> <tr> <td style="border:none; text-align:left">3.<input type=checkbox> <script type="math/tex">\left(\begin{array}{rrr} \frac{113}{4} & 0 & -\frac{35}{2} \\ 0 & 4 & 0 \\ -\frac{35}{2} & 0 & \frac{53}{4}\end{array}\right)</script>    </td> <td style="border:none; text-align:left">4.<input type=checkbox> <script type="math/tex">\left(\begin{array}{rrr} -\frac{25}{4} & -2 & \frac{3}{2} \\ -2 & -\frac{13}{4} & -3 \\ \frac{3}{2} & -3 & -5\end{array}\right)</script>    </td> </tr> </table><br><br><b> <span style="color: #ff0000;">Respuesta al apartado 2 </span></b><br><br> <table style=" width:100%"> <tr> <td style="border:none; text-align:left">1.<input type=checkbox> <script type="math/tex">{\rm rang}(B)={\rm rang}(C)=2</script>.    </td> <td style="border:none; text-align:left">2.<input type=checkbox> <script type="math/tex">{\rm rang}(B)=3</script> y <script type="math/tex">{\rm rang}(C)=2</script>.    </td> </tr> <tr> <td style="border:none; text-align:left">3.<input type=checkbox> <script type="math/tex">{\rm rang}(B)=2</script> y <script type="math/tex">{\rm rang}(C)=3</script>.    </td> <td style="border:none; text-align:left">4.<input type=checkbox> <script type="math/tex">{\rm rang}(B)={\rm rang}(C)=3</script>.    </td> </tr> </table><br><br><b> <span style="color: #ff0000;">Respuesta al apartado 3 </span></b><br><br> 1.<input type=checkbox> El sistema tiene solución única: <script type="math/tex">x=-3,\,y=0\,z=-1</script> <br> 2.<input type=checkbox> El conjunto de soluciones es <script type="math/tex; mode=display">\begin{array}{ccl}x & = & 1+\frac{1}{12}\alpha\\ y & = & 1-\frac{1}{6}\alpha\\ z & = & \alpha\end{array}</script>. <br> 3.<input type=checkbox> El sistema tiene solución única: <script type="math/tex">x=\frac{1}{3},\,y=-\frac{5}{3}\,z=0</script> <br> 4.<input type=checkbox> El sistema tiene solución única: <script type="math/tex">x=1,\,y=1\,z=0</script><br><br><b> <span style="color: #ff0000;">Respuesta al apartado 4 </span></b><br>

In [14]:
# EJERCICIO 1
# QTICI__IB
# Definir la matriz:
A = matrix([[-1, 1, 1/4],[2, 1, 0],[3, 0, -1/4]])
A

[  -1    1  1/4]
[   2    1    0]
[   3    0 -1/4]

[  -2    1    0]
[  -1   -1    0]
[ 1/2    0 -1/2]

In [16]:
# Definir la matriz:
S = matrix([[3, 1, 0],[6, 2, 1],[-1, -1/3, 2]])
S
t = vector([3, 5, -3])
S.solve_right(b)

ValueError: matrix equation has no solutions

In [5]:
#1 Calcular (S-St)2.
# Transpuesta, calculo y mostrar: 
St = S.transpose()
F = (S - St)^2
show(F)

[   -26   -4/3  -20/3]
[  -4/3 -241/9      5]
[ -20/3      5  -25/9]

In [6]:
#2 Estudiar el rango de las matrices B=(A−At)2 y C=(S+St)2.
# Transpuesta, calculo y mostrar:
At = A.transpose()
B = (A - At)^2
C = (S + St)^2
# Propiedad: rango: 
print("rango B:", B.rank())
print("rango C:", C.rank())

rango B: 2
rango C: 3


In [13]:
#3 Hallar el conjunto de soluciones del sistema de ecuaciones lineales Ax=b.
# Definir un vector y resolver por la derecha:
t = vector([3, 5, -3])
S.solve_right(b)

ValueError: matrix equation has no solutions

In [10]:
#4 Hallar el conjunto de soluciones del sistema de ecuaciones lineales Ax=t.
# Definir un vector y resolver por la derecha:
t = vector([3, 5, -3])
S.solve_right(t)

(1, 0, -1)

In [9]:
#5 Hallar el conjunto de soluciones del sistema de ecuaciones lineales Sx=b.
# Resolver por la derecha:
S.solve_right(b)

ValueError: matrix equation has no solutions

In [18]:
# EJERCICIO 2
#1 Almacenar los datos trabajando con números en coma flotante para 22 bits en la mantisa y calcular entonces el valor del determinante.
# Definir la matriz:
A = matrix([[-23, -35, 13, -42],[18, 4, -29, -15],[-28, 34, -19, 37],[23, 40, -48, -33]])
# 22 bits en la mantisa:
B = A.change_ring(RealField(22))
# Mostrar el determinante:
print(B.det())

2.98300e6


In [19]:
#2 Almacenar los datos trabajando con números enteros modulares Z29 y hallar B=A−1. Indicar el valor obtenido para el elemento b4,4.
# Modulo Z29:
mod = A.change_ring(IntegerModRing(29))
# Calcular la inversa y mostrarla:
B = mod.inverse()
show(B)

[ 7 27 18 28]
[10  1 15  1]
[10  9 26 22]
[13 21 14  1]

In [138]:
# EJERCICIO 3
#1 Averiguar los pesos de los flujos de los nodos de la red proporcionada con el exterior si los 
#flujos de las calles del enunciado son [-600, 300, -300, 800, -300, 700, 200], respectivamente. 
A = matrix(QQ,
[
[0, 0, 1, 0, 1, 0, 0, -600],
[0, 1, 0, 0, 1, -1, 0, 300],
[0, 0, 0, 0, 0, 1, -1, -300],
[-1, 0, 0, 0, 0, 0, 1, 1100],
[-1, 1, 0, 1, 0, 0, 0, 0],
[0, 0, 1, 1, 0, 0, 0, 900]
])
show(A)

[   0    0    1    0    1    0    0 -600]
[   0    1    0    0    1   -1    0  300]
[   0    0    0    0    0    1   -1 -300]
[  -1    0    0    0    0    0    1 1100]
[  -1    1    0    1    0    0    0    0]
[   0    0    1    1    0    0    0  900]

In [139]:
F, U = forma_escalonada(A, True)


Forma escalonada canónica:
[ 1  0  0  0  0  0 -1  0]
[ 0  1  0  0  1  0 -1  0]
[ 0  0  1  0  1  0  0  0]
[ 0  0  0  1 -1  0  0  0]
[ 0  0  0  0  0  1 -1  0]
[ 0  0  0  0  0  0  0  1]


In [62]:
pistas = "SECRET"+"MYCODE"
cifrado_pistas = [alfabeto.index(i) for i in pistas]
show(cifrado_pistas)

[19, 4, 2, 18, 4, 20, 12, 25, 2, 15, 3, 4]

In [63]:
pistas_codificadas = "WKRSJY"+"YDTSMG"
cifrado_pistas_codificadas = [alfabeto.index(i) for i in pistas_codificadas]
show(cifrado_pistas_codificadas)

[23, 10, 18, 19, 9, 25, 25, 3, 20, 19, 12, 6]

In [64]:
M = matrix(IntegerModRing(29),
[
[19, 4, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 19, 4, 2, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 19, 4, 2, 0, 0, 1],
[18, 4, 20, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 18, 4, 20, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 18, 4, 20, 0, 0, 1],
[12, 25, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 12, 25, 2, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 12, 25, 2, 0, 0, 1],
[15, 3, 4, 0, 0, 0, 0, 0, 0, 1, 0, 0],
[0, 0, 0, 15, 3, 4, 0, 0, 0, 0, 1, 0],
[0, 0, 0, 0, 0, 0, 15, 3, 4, 0, 0, 1]
]).augment(column_matrix(IntegerModRing(29),cifrado_pistas_codificadas))
show(M)

[19  4  2  0  0  0  0  0  0  1  0  0 23]
[ 0  0  0 19  4  2  0  0  0  0  1  0 10]
[ 0  0  0  0  0  0 19  4  2  0  0  1 18]
[18  4 20  0  0  0  0  0  0  1  0  0 19]
[ 0  0  0 18  4 20  0  0  0  0  1  0  9]
[ 0  0  0  0  0  0 18  4 20  0  0  1 25]
[12 25  2  0  0  0  0  0  0  1  0  0 25]
[ 0  0  0 12 25  2  0  0  0  0  1  0  3]
[ 0  0  0  0  0  0 12 25  2  0  0  1 20]
[15  3  4  0  0  0  0  0  0  1  0  0 19]
[ 0  0  0 15  3  4  0  0  0  0  1  0 12]
[ 0  0  0  0  0  0 15  3  4  0  0  1  6]

In [65]:
F, U = forma_escalonada(M, True)


Forma escalonada canónica:
[ 1  0  0  0  0  0  0  0  0  0  0  0  3]
[ 0  1  0  0  0  0  0  0  0  0  0  0  8]
[ 0  0  1  0  0  0  0  0  0  0  0  0  8]
[ 0  0  0  1  0  0  0  0  0  0  0  0 24]
[ 0  0  0  0  1  0  0  0  0  0  0  0 27]
[ 0  0  0  0  0  1  0  0  0  0  0  0 19]
[ 0  0  0  0  0  0  1  0  0  0  0  0  9]
[ 0  0  0  0  0  0  0  1  0  0  0  0 10]
[ 0  0  0  0  0  0  0  0  1  0  0  0 17]
[ 0  0  0  0  0  0  0  0  0  1  0  0  5]
[ 0  0  0  0  0  0  0  0  0  0  1  0 17]
[ 0  0  0  0  0  0  0  0  0  0  0  1  5]


In [66]:
#SOBJB_PYG
A = matrix(IntegerModRing(29),3,3,list(U.column(12)[0:9]))
show(A)
b = vector(IntegerModRing(29),list(U.column(12)[9:]))
show(b)


[ 3  8  8]
[24 27 19]
[ 9 10 17]

(5, 17, 5)

In [67]:
Ai = A.inverse()

In [82]:
mensaje_codificado = "XKDWYQSSK"
cifrado_mensaje = [alfabeto.index(i) for i in mensaje_codificado]
cifrado_mensaje

[24, 10, 3, 23, 25, 17, 19, 19, 10]

In [84]:
x1 = list(Ai*(vector(IntegerModRing(29),cifrado_mensaje[0:3])-b))
x2 = list(Ai*(vector(IntegerModRing(29),cifrado_mensaje[3:6])-b))
x3 = list(Ai*(vector(IntegerModRing(29),cifrado_mensaje[6:9])-b))

In [85]:
descifrado_mensaje = x1+x2+x3
descifrado_mensaje

[18, 4, 17, 21, 8, 19, 8, 20, 15]

In [86]:
mensaje_original = ""
for i in descifrado_mensaje:
    mensaje_original = mensaje_original + alfabeto[i]
    
mensaje_original

'REQUISITO'